"""Validate M1-M5 artifacts and build the M6 report and primary figures."""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Final

os.environ.setdefault(
    "MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "qqq-volatility-matplotlib")
)
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

if __package__ in {None, ""}:  # pragma: no cover
    project_root = Path(__file__).resolve().parents[1]
    if str(project_root) not in sys.path:
        sys.path.insert(0, str(project_root))

from config import (
    EXPERIMENT_DATASET_REPORT_PATH,
    NON_SPIKE_TRAIN_PATH,
    SPIKE_ANALYSIS_REPORT_PATH,
    SPIKE_DAILY_RETURN_FIGURE_PATH,
    SPIKE_DATASET_COMPARISON_FIGURE_PATH,
    SPIKE_INPUT_CONTRACT_REPORT_PATH,
    SPIKE_VOLATILITY_EFFECT_FIGURE_PATH,
    TEST_FLAGGED_PATH,
    TEST_LABELED_DATA_PATH,
    TRAIN_LABELED_DATA_PATH,
    VALIDATION_FLAGGED_PATH,
    VALIDATION_LABELED_DATA_PATH,
    WITH_SPIKES_TRAIN_PATH,
)
from src.build_experiment_datasets import (
    DIAGNOSTIC_COLUMNS,
    ExperimentDatasetPaths,
    _validate_m1_contract,
    build_primary_experiment_frames,
)
from src.build_spike_input_contract import (
    _same_path,
    _sha256,
    _strict_json_load,
    _write_and_verify_report,
    load_labeled_split,
)
from src.build_targets import CLASSIFICATION_TARGET, TARGET_COLUMN
from src.report_paths import report_relative_path

SPLIT_NAMES: Final = ("train", "validation", "test")
REPORT_VERSION: Final = 1


@dataclass(frozen=True, slots=True)
class SpikeReportPaths:
    """Protected M1-M5 inputs and the three artifacts generated by M6."""

    train_labeled: Path
    validation_labeled: Path
    test_labeled: Path
    input_contract: Path
    spike_analysis: Path
    daily_return_figure: Path
    with_spikes_train: Path
    non_spike_train: Path
    validation_flagged: Path
    test_flagged: Path
    dataset_report: Path
    volatility_figure: Path
    comparison_figure: Path

    @classmethod
    def defaults(cls) -> SpikeReportPaths:
        return cls(
            TRAIN_LABELED_DATA_PATH,
            VALIDATION_LABELED_DATA_PATH,
            TEST_LABELED_DATA_PATH,
            SPIKE_INPUT_CONTRACT_REPORT_PATH,
            SPIKE_ANALYSIS_REPORT_PATH,
            SPIKE_DAILY_RETURN_FIGURE_PATH,
            WITH_SPIKES_TRAIN_PATH,
            NON_SPIKE_TRAIN_PATH,
            VALIDATION_FLAGGED_PATH,
            TEST_FLAGGED_PATH,
            EXPERIMENT_DATASET_REPORT_PATH,
            SPIKE_VOLATILITY_EFFECT_FIGURE_PATH,
            SPIKE_DATASET_COMPARISON_FIGURE_PATH,
        )

    @classmethod
    def under_output_root(cls, output_root: str | Path) -> SpikeReportPaths:
        base = Path(output_root)
        defaults = cls.defaults()
        return cls(
            defaults.train_labeled,
            defaults.validation_labeled,
            defaults.test_labeled,
            defaults.input_contract,
            defaults.spike_analysis,
            defaults.daily_return_figure,
            defaults.with_spikes_train,
            defaults.non_spike_train,
            defaults.validation_flagged,
            defaults.test_flagged,
            base / "outputs" / "reports" / "experiment_dataset_report.json",
            base
            / "outputs"
            / "figures"
            / "spike_analysis"
            / "volatility_spike_effect.png",
            base / "outputs" / "figures" / "spike_analysis" / "dataset_comparison.png",
        )

    def labeled_inputs(self) -> dict[str, Path]:
        return {
            "train": self.train_labeled,
            "validation": self.validation_labeled,
            "test": self.test_labeled,
        }

    def protected_inputs(self) -> dict[str, Path]:
        return {
            **{f"{key}_labeled": value for key, value in self.labeled_inputs().items()},
            "spike_input_contract": self.input_contract,
            "spike_analysis": self.spike_analysis,
            "daily_return_figure": self.daily_return_figure,
            "with_spikes_train": self.with_spikes_train,
            "non_spike_train": self.non_spike_train,
            "validation_flagged": self.validation_flagged,
            "test_flagged": self.test_flagged,
        }

    def generated_outputs(self) -> dict[str, Path]:
        return {
            "experiment_dataset_report": self.dataset_report,
            "volatility_spike_effect_figure": self.volatility_figure,
            "dataset_comparison_figure": self.comparison_figure,
        }


def _preflight(paths: SpikeReportPaths, *, overwrite_generated: bool) -> None:
    protected = paths.protected_inputs()
    outputs = paths.generated_outputs()
    for name, path in protected.items():
        if not path.is_file():
            raise FileNotFoundError(f"Missing protected M6 input {name}: {path}")
    for output_name, output in outputs.items():
        for source_name, source in protected.items():
            if _same_path(output, source):
                raise ValueError(f"M6 output {output_name} aliases {source_name}")
    if len({_path.resolve(strict=False) for _path in outputs.values()}) != len(outputs):
        raise ValueError("M6 outputs must be distinct")
    existing = [
        (name, path)
        for name, path in outputs.items()
        if path.exists() or path.is_symlink()
    ]
    if any(path.is_dir() for _, path in existing):
        raise ValueError("An M6 output path is an existing directory")
    if existing and not overwrite_generated:
        raise FileExistsError("M6 outputs already exist; use --overwrite-generated")
    if overwrite_generated:
        for name, path in existing:
            if path.is_symlink() or path.stat().st_nlink > 1:
                raise ValueError(f"Refusing to overwrite aliased M6 output: {name}")


def _read_csv(path: Path, *, flagged: bool = False) -> pd.DataFrame:
    frame = pd.read_csv(path)
    required = {"Date", CLASSIFICATION_TARGET}
    if flagged:
        required.update(DIAGNOSTIC_COLUMNS)
    if missing := sorted(required.difference(frame.columns)):
        raise ValueError(f"{path.name} missing required columns: {missing}")
    frame["Date"] = pd.to_datetime(frame["Date"], errors="raise")
    return frame


def _class_summary(frame: pd.DataFrame) -> dict[str, Any]:
    counts = frame[CLASSIFICATION_TARGET].astype(int).value_counts()
    total = len(frame)
    return {
        "rows": total,
        "date_range": {
            "start": frame["Date"].iloc[0].date().isoformat(),
            "end": frame["Date"].iloc[-1].date().isoformat(),
        },
        "class_counts": {"0": int(counts.get(0, 0)), "1": int(counts.get(1, 0))},
        "class_ratios": {
            "0": float(counts.get(0, 0) / total),
            "1": float(counts.get(1, 0) / total),
        },
    }


def _atomic_figure(figure: plt.Figure, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        prefix=f".{path.stem}.", suffix=".png", dir=path.parent, delete=False
    ) as handle:
        temporary = Path(handle.name)
    try:
        figure.savefig(temporary, dpi=150, metadata={"Software": "QQQ Phase 2 M6"})
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)
        plt.close(figure)


def _plot_volatility(
    frames: Mapping[str, pd.DataFrame], built: Any, path: Path
) -> None:
    figure, axes = plt.subplots(3, 1, figsize=(14, 11))
    for axis, split in zip(axes, SPLIT_NAMES, strict=True):
        frame = frames[split]
        result = built.affected_results[split]
        axis.plot(
            frame["Date"],
            frame["historical_volatility_20d"],
            label="Historical volatility 20d (feature)",
            linewidth=1,
        )
        axis.plot(
            frame["Date"],
            frame[TARGET_COLUMN],
            label="Future volatility 5d (target)",
            linewidth=1,
        )
        for window in result.windows:
            axis.axvspan(
                frame["Date"].iloc[window.clipped_start],
                frame["Date"].iloc[window.clipped_end],
                color="gold",
                alpha=0.12,
            )
        direct = result.direct_flags.to_numpy(dtype=bool)
        axis.scatter(
            frame.loc[direct, "Date"],
            frame.loc[direct, TARGET_COLUMN],
            color="crimson",
            s=22,
            zorder=3,
            label=f"Direct spikes ({int(direct.sum())})",
        )
        axis.set_title(
            f"{split.capitalize()}: {frame['Date'].iloc[0].date()} to {frame['Date'].iloc[-1].date()}"
        )
        axis.set_ylabel("Volatility (decimal)")
        axis.grid(alpha=0.2)
        axis.legend(loc="best")
    axes[-1].set_xlabel("Date")
    figure.suptitle("Volatility around split-local direct-spike affected windows")
    figure.tight_layout()
    _atomic_figure(figure, path)


def _plot_comparison(summaries: Mapping[str, Mapping[str, Any]], path: Path) -> None:
    names = [
        "Original Train",
        "With-Spike Train",
        "Operationally Non-Spike-Affected Train",
    ]
    keys = ["original_train", "with_spikes_train", "non_spike_train"]
    rows = [summaries[key]["rows"] for key in keys]
    zeros = [summaries[key]["class_counts"]["0"] for key in keys]
    ones = [summaries[key]["class_counts"]["1"] for key in keys]
    figure, axes = plt.subplots(1, 2, figsize=(14, 6))
    bars = axes[0].bar(names, rows, color=["0.45", "tab:blue", "tab:orange"])
    axes[0].bar_label(bars)
    axes[0].set_title("Training dataset row counts")
    axes[0].set_ylabel("Rows")
    axes[0].tick_params(axis="x", rotation=15)
    axes[1].bar(names, zeros, label="Class 0")
    axes[1].bar(names, ones, bottom=zeros, label="Class 1")
    for index, (zero_count, one_count) in enumerate(zip(zeros, ones, strict=True)):
        total = zero_count + one_count
        axes[1].text(
            index,
            zero_count / 2,
            f"{zero_count}\n({zero_count / total:.1%})",
            ha="center",
            va="center",
            color="white",
        )
        axes[1].text(
            index,
            zero_count + one_count / 2,
            f"{one_count}\n({one_count / total:.1%})",
            ha="center",
            va="center",
            color="white",
        )
    axes[1].set_title("Frozen-Q75 class counts")
    axes[1].set_ylabel("Rows")
    axes[1].tick_params(axis="x", rotation=15)
    axes[1].legend()
    figure.suptitle("Primary Train dataset comparison (Validation/Test remain full)")
    figure.tight_layout()
    _atomic_figure(figure, path)


def run_spike_report_pipeline(
    paths: SpikeReportPaths, *, overwrite_generated: bool = False
) -> dict[str, Any]:
    """Validate dependencies, create M6 artifacts, and preserve every input."""
    _preflight(paths, overwrite_generated=overwrite_generated)
    before = {name: _sha256(path) for name, path in paths.protected_inputs().items()}
    contract = _strict_json_load(paths.input_contract)
    audit = _strict_json_load(paths.spike_analysis)
    if (
        audit.get("overall_data_quality_status") != "internally_consistent"
        or audit.get("audit_findings")
        or audit.get("review_items")
    ):
        raise RuntimeError("M4 contains unresolved data-quality findings")
    frames = {
        name: load_labeled_split(path, name)
        for name, path in paths.labeled_inputs().items()
    }
    m5_paths = ExperimentDatasetPaths.defaults()
    _validate_m1_contract(frames, m5_paths, contract)
    for name in (
        "train_labeled",
        "validation_labeled",
        "test_labeled",
        "spike_input_contract",
    ):
        if audit["inputs"][name]["sha256"] != before[name]:
            raise ValueError(f"M4 input checksum is stale: {name}")
    if (
        audit["generated_artifacts"]["daily_return_figure"]["sha256"]
        != before["daily_return_figure"]
    ):
        raise ValueError("M4 daily-return figure checksum mismatch")
    built = build_primary_experiment_frames(frames)
    if asdict(built.fitted_detector) != audit["primary_detector"]:
        raise ValueError("M2 detector metadata differs from M4 report")
    for split in SPLIT_NAMES:
        observed = asdict(built.affected_results[split].summary)
        if any(
            audit["splits"][split].get(key) != value for key, value in observed.items()
        ):
            raise ValueError(f"M3 {split} result differs from M4 report")

    artifacts = {
        "with_spikes_train": _read_csv(paths.with_spikes_train),
        "non_spike_train": _read_csv(paths.non_spike_train),
        "validation_flagged": _read_csv(paths.validation_flagged, flagged=True),
        "test_flagged": _read_csv(paths.test_flagged, flagged=True),
    }
    if paths.with_spikes_train.read_bytes() != paths.train_labeled.read_bytes():
        raise ValueError("With-Spike Train is not byte-identical to Original Train")
    expected_non_spike = built.non_spike_train.reset_index(drop=True)
    pd.testing.assert_frame_equal(
        artifacts["non_spike_train"],
        expected_non_spike,
        check_dtype=False,
        rtol=1e-12,
        atol=1e-12,
    )
    for split in ("validation", "test"):
        pd.testing.assert_frame_equal(
            artifacts[f"{split}_flagged"],
            getattr(built, f"{split}_flagged"),
            check_dtype=False,
            rtol=1e-12,
            atol=1e-12,
        )

    classification_threshold = float(contract["classification_contract"]["threshold"])
    for name, frame in artifacts.items():
        expected_labels = frame[TARGET_COLUMN].gt(classification_threshold).astype(int)
        if not frame[CLASSIFICATION_TARGET].astype(int).equals(expected_labels):
            raise ValueError(f"{name} labels differ from frozen Original Q75")
    summaries = {
        "original_train": _class_summary(frames["train"]),
        "with_spikes_train": _class_summary(artifacts["with_spikes_train"]),
        "non_spike_train": _class_summary(artifacts["non_spike_train"]),
    }
    _plot_volatility(frames, built, paths.volatility_figure)
    _plot_comparison(summaries, paths.comparison_figure)
    diagnostic = {
        split: {
            "full": len(artifacts[f"{split}_flagged"]),
            "non_spike": int(
                (~artifacts[f"{split}_flagged"]["is_spike_affected"]).sum()
            ),
            "spike_affected": int(
                artifacts[f"{split}_flagged"]["is_spike_affected"].sum()
            ),
        }
        for split in ("validation", "test")
    }
    report: dict[str, Any] = {
        "report_version": REPORT_VERSION,
        "paths_relative_to": "report_directory",
        "dataset_definition": "operationally non-spike-affected",
        "classification_contract": {
            "source": "Original Train",
            "quantile": contract["classification_contract"]["quantile"],
            "quantile_method": contract["classification_contract"]["quantile_method"],
            "threshold": classification_threshold,
            "comparison_rule": contract["classification_contract"]["comparison_rule"],
            "labels_consistent": True,
        },
        "datasets": summaries,
        "diagnostic_segments": diagnostic,
        "evaluation_contract": {
            "primary_validation": "full Original Validation",
            "primary_test": "full Original Test",
            "flagged_copies_role": "diagnostic_only",
        },
        "spike_counts": {
            split: {
                "direct": built.affected_results[split].summary.direct_count,
                "affected": built.affected_results[split].summary.affected_union_count,
            }
            for split in SPLIT_NAMES
        },
        "train_filtering": {
            "before": len(frames["train"]),
            "removed": int(built.affected_results["train"].affected_flags.sum()),
            "retained": len(artifacts["non_spike_train"]),
            "identity_valid": len(frames["train"])
            == int(built.affected_results["train"].affected_flags.sum())
            + len(artifacts["non_spike_train"]),
        },
        "artifacts": {
            name: {
                "path": report_relative_path(path, paths.dataset_report),
                "sha256": _sha256(path),
            }
            for name, path in {
                **paths.protected_inputs(),
                "volatility_spike_effect_figure": paths.volatility_figure,
                "dataset_comparison_figure": paths.comparison_figure,
            }.items()
        },
        "limitations": {
            "boundary": built.affected_results["train"].summary.boundary_limitation,
            "rsi": built.affected_results["train"].summary.rsi_limitation,
            "interpretation": "Non-Spike Train is operationally non-spike-affected under [s-5, s+19], not proven free of spike influence in every feature.",
        },
        "expected_audit_checks": {
            "role": "regression_assertions_not_calculation_inputs",
            "train_rows": {"before": 1733, "after": 1520},
            "direct_affected": {
                "train": [19, 213],
                "validation": [0, 0],
                "test": [4, 54],
            },
            "non_spike_class_counts": {"0": 1240, "1": 280},
        },
    }
    observed_pinned = (
        len(frames["train"]),
        len(artifacts["non_spike_train"]),
        summaries["non_spike_train"]["class_counts"],
    )
    if observed_pinned != (1733, 1520, {"0": 1240, "1": 280}):
        raise RuntimeError(f"Pinned baseline regression drift: {observed_pinned}")
    _write_and_verify_report(report, paths.dataset_report)
    after = {name: _sha256(path) for name, path in paths.protected_inputs().items()}
    if after != before:
        raise RuntimeError("A protected M1-M5 artifact changed during M6")
    return report


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build Phase 2 M6 reports and figures")
    parser.add_argument("--output-root", type=Path)
    parser.add_argument("--overwrite-generated", action="store_true")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    paths = (
        SpikeReportPaths.defaults()
        if args.output_root is None
        else SpikeReportPaths.under_output_root(args.output_root)
    )
    try:
        report = run_spike_report_pipeline(
            paths, overwrite_generated=args.overwrite_generated
        )
    except Exception as error:  # noqa: BLE001 - CLI converts validation failures
        partial = [
            str(path) for path in paths.generated_outputs().values() if path.exists()
        ]
        print(f"M6 failed: {error}; partial_outputs={partial}", file=sys.stderr)
        return 1
    print(
        f"M6 complete: report={paths.dataset_report}; train={report['train_filtering']}"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
